version: "3.8"

services:

  app-ui:
    image: storage-ui:0.0.1
    build: ./storage-ui
    restart: always
    ports:
      - '80:80'
    volumes:
      - /app/node_modules
      - ./storage-ui:/app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./docker-env/storage-back.env
    ports:
      - "8080:8080"
    volumes:
      - "./files:/app/files"
    depends_on:
      - db

  db:
    image: postgres:14.7-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./docker-env/postgresql.env
    volumes:
      - pgdb-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER
      interval: 1s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgdb-data:
  pgadmin-data: