
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: make start
    environment:
      - SPRING_DATASOURCE_URL=jdbc
    ports:
      - "8080:8080"
    volumes:
      - "~/files:~/files"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: storage
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data